### ISSUE TITLE
add claude-2-100k model

### ISSUE THREAD

**Issue by xRiddin** [AshwinPathi/claude-api-py#11]
if it's possible to add claude-2-100k model that would be very appreciated..

**Comment by AshwinPathi** [comment]
yep, work in progress.

**Comment by AshwinPathi** [comment]
@xRiddin Is this model accessible through the UI?

**Comment by xRiddin** [comment]
i just know it's claude 2 but not sure if it's 100k model, most probably not a 100k model

**Comment by winie-hy** [comment]
no， As far as I know, only slack is open

**Comment by AshwinPathi** [comment]
Hm, I tried sending a message with a model string other than the default one and it errored out on me. If you have time could you also experiment with it?

 iirc this seems to be the only change but I cant really verify thats all i need since I can only send claude 2 model requests via the chat app (which is what I'm reverse engineering).

**Comment by xRiddin** [comment]
> no， As far as I know, only slack is open

slack got claude2 100k model??

**Comment by AshwinPathi** [comment]
@xRiddin I added a few more models. Note that some of the models require a pro subscription to use.
